ROOT := ../..

.DEFAULT_GOAL := help

.PHONY: help list status

help:
	@cd $(ROOT) && ./scripts/list-skills.sh help

list:
	@cd $(ROOT) && ./scripts/list-skills.sh list

status:
	@cd $(ROOT) && ./scripts/list-skills.sh status
