AWSTemplateFormatVersion: "2010-09-09"
Description: Open Kata website infrastructure

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: openkata-web-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: openkata-web
      Runtime: provided.al2023
      Architectures:
        - arm64
      Handler: bootstrap
      Code:
        ZipFile: placeholder
      Role: !GetAtt LambdaRole.Arn
      MemorySize: 128
      Timeout: 10

  FunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt LambdaFunction.Arn
      AuthType: NONE

  FunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  FunctionUrl:
    Description: Public URL for the website
    Value: !GetAtt FunctionUrl.FunctionUrl
