// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Nav().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <main><section class=\"hero hero--kanji\"><span class=\"hero-kanji\">型</span><div class=\"hero-text\"><h1 class=\"cursor\">OpenKata</h1><p class=\"comment\">Codified practices for AI agents — teach your agents the way.</p></div></section><div class=\"logo-section\"><img src=\"/static/img/logo.webp\" alt=\"OpenKata logo\" class=\"site-logo site-logo--light\"> <img src=\"/static/img/logo-dark.webp\" alt=\"OpenKata logo\" class=\"site-logo site-logo--dark\"></div><h2>About</h2><p>What was implicit craft must become codified practice. Open Kata turns engineering knowledge into portable, reusable workflows that AI agents can follow — so good patterns are shared, not lost.</p><p>A collection of platform-agnostic skills and rules that work with any agent supporting the <a href=\"https://agentskills.io/\" target=\"_blank\" rel=\"noopener\">Agent Skills specification</a>. No vendor lock-in. No build step. Just files.</p><h2>Connect Your Agent</h2><p>Grounding your agent context with the OpenKata knowledge base.</p><h3>Model Context Protocol (MCP)</h3><p>AI agents can connect directly to browse, search, and retrieve OpenKata content via the /mcp endpoint.</p><p>Server endpoint: <code>https://openkata.dev/mcp</code></p><p class=\"comment\">We suggest enabling the MCP only when scaffolding a new project or maintaining agentic structure.</p><h3>Downloadable Static Skills</h3><p>For offline or local-first workflows, download skills from this site and drop them into your repository to give your local agent OpenKata superpowers.</p></main><footer class=\"footer\">© 2026 OPENKATA.dev // License: <a href=\"https://github.com/tovrleaf/openkata/blob/main/LICENSE\" target=\"_blank\" rel=\"noopener\">MIT</a></footer>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Home").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
