// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"nav\"><img src=\"/static/img/icon.webp\" alt=\"\" class=\"nav-icon\"> <a href=\"/\" class=\"nav-brand\">OPENKATA.dev</a><div class=\"nav-links\"><a href=\"/skills/\" class=\"nav-link\">Skills</a> <a href=\"/rules/\" class=\"nav-link\">Rules</a> <a href=\"/profiles/\" class=\"nav-link\">Profiles</a></div><div class=\"nav-actions\"><button id=\"search-open-btn\" class=\"search-btn\" aria-label=\"Search\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 50 50\" fill=\"currentColor\" width=\"20\" height=\"20\"><path d=\"M21 3C11.6 3 4 10.6 4 20s7.6 17 17 17c3.7 0 7.1-1.2 9.9-3.2l13.1 13.1 2.1-2.1L33 31.8c2-2.8 3.2-6.2 3.2-9.9C36.2 11.6 31.4 3 21 3zm0 2c8.7 0 15 7.3 15 15s-6.3 15-15 15S6 28.7 6 20 12.3 5 21 5z\"></path></svg></button><div class=\"theme-switcher\"><button class=\"theme-switcher__btn\" onclick=\"cycleTheme()\" aria-label=\"Next theme\"></button></div></div></nav><div id=\"search-overlay\" class=\"search-overlay\" hidden><div class=\"search-overlay__backdrop\"></div><div class=\"search-overlay__panel\"><div class=\"search-overlay__header\"><input type=\"text\" id=\"search-input\" class=\"search-overlay__input\" placeholder=\"Search...\" autocomplete=\"off\"> <button id=\"search-close-btn\" class=\"search-overlay__close\" aria-label=\"Close search\">&times;</button></div><div id=\"search-results\" class=\"search-overlay__results\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
