name: Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::152406482128:role/openkata-ci
          aws-region: eu-north-1

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Deploy
        run: ./scripts/deploy.sh
