root = "../.."
tmp_dir = "tmp"

[build]
  cmd = "~/go/bin/templ generate ./cmd/openkata-web/templates/ && go build -o ./tmp/openkata-web ./cmd/openkata-web/"
  bin = "./tmp/openkata-web"
  include_ext = ["go", "templ", "css"]
  exclude_dir = ["tmp", "node_modules", ".git", "bin"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
